version: '3.8'

services:
  db:
    image: postgres
    restart: always
    networks:
      - dbnet
    environment: 
      POSTGRES_PASSWORD: admin
  front:
    build: ./front
    networks:
      - intranet
    ports:
      - 5000:5000
  api:
    build: .
    networks:
      - intranet
      - dbnet
    ports:
      - 8080:8080
    environment: 
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db
networks:
  intranet:
  dbnet:
